export const TRANSACTION_TYPES = {
  CASH: 'CASH',
  WEEKLY_CREDIT: 'WEEKLY_CREDIT',
  LAYAWAY: 'LAYAWAY',
  LOAN: 'LOAN',
};

export const TRANSACTION_TYPE_LABELS = {
  [TRANSACTION_TYPES.CASH]: 'Venta de contado',
  [TRANSACTION_TYPES.WEEKLY_CREDIT]: 'Crédito semanal',
  [TRANSACTION_TYPES.LAYAWAY]: 'Apartado',
  [TRANSACTION_TYPES.LOAN]: 'Préstamo',
};

export const TRANSACTION_TYPE_SHORT_LABELS = {
  [TRANSACTION_TYPES.CASH]: 'Venta',
  [TRANSACTION_TYPES.WEEKLY_CREDIT]: 'Crédito',
  [TRANSACTION_TYPES.LAYAWAY]: 'Apartar',
  [TRANSACTION_TYPES.LOAN]: 'Prestar',
};
