import { Platform, StatusBar, StyleSheet } from 'react-native';
import { theme } from '../../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  loader: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.background,
  },
  scrollContent: {
    paddingBottom: 32,
  },
  header: {
    backgroundColor: theme.colors.white,
    paddingHorizontal: 20,
    paddingTop: (Platform.OS === 'android' ? StatusBar.currentHeight || 0 : 0) + 18,
    paddingBottom: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  avatarRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerText: {
    flex: 1,
    minWidth: 0,
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: theme.colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarImage: {
    width: 56,
    height: 56,
    borderRadius: 28,
  },
  greeting: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    fontWeight: '600',
  },
  name: {
    fontSize: 20,
    color: theme.colors.text,
    fontWeight: '800',
  },
  meta: {
    marginTop: 2,
    fontSize: 12,
    color: theme.colors.textSecondary,
    flexShrink: 1,
  },
  logoutButton: {
    minHeight: 44,
    paddingHorizontal: 12,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#fff0f6',
    borderWidth: 1,
    borderColor: '#fcc2d7',
  },
  logoutText: {
    color: theme.colors.primary,
    fontSize: 13,
    fontWeight: '800',
  },
  statusCard: {
    marginHorizontal: 20,
    marginTop: 18,
    padding: 14,
    borderRadius: 12,
    backgroundColor: '#f8f9fa',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  statusTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  statusLabel: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    fontWeight: '700',
  },
  statusValue: {
    marginTop: 2,
    fontSize: 16,
    color: theme.colors.text,
    fontWeight: '800',
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  statusBadgeText: {
    color: theme.colors.white,
    fontSize: 11,
    fontWeight: '800',
  },
  lastPaymentBox: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
  },
  lastPaymentTitle: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    fontWeight: '800',
    marginBottom: 8,
  },
  lastPaymentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  lastPaymentDateBlock: {
    alignItems: 'flex-end',
  },
  lastPaymentLabel: {
    fontSize: 11,
    color: theme.colors.textSecondary,
    fontWeight: '700',
    marginBottom: 2,
  },
  lastPaymentValue: {
    fontSize: 14,
    color: theme.colors.text,
    fontWeight: '800',
  },
  section: {
    paddingHorizontal: 20,
    marginTop: 18,
  },
  cardsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  metricCard: {
    flexGrow: 1,
    flexBasis: '47%',
    minHeight: 104,
    backgroundColor: theme.colors.white,
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  metricIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  metricValue: {
    fontSize: 18,
    fontWeight: '800',
    color: theme.colors.text,
  },
  metricLabel: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: '700',
    color: theme.colors.textSecondary,
    textTransform: 'uppercase',
  },
  tabs: {
    flexDirection: 'row',
    backgroundColor: theme.colors.white,
    marginHorizontal: 20,
    marginTop: 18,
    padding: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  tabButton: {
    flex: 1,
    minHeight: 40,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabButtonActive: {
    backgroundColor: '#fff0f6',
  },
  tabText: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.colors.textSecondary,
  },
  tabTextActive: {
    color: theme.colors.primary,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: theme.colors.text,
    marginBottom: 10,
  },
  transactionCard: {
    backgroundColor: theme.colors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: 14,
    marginBottom: 10,
  },
  transactionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  transactionIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  transactionMain: {
    flex: 1,
  },
  transactionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: theme.colors.text,
  },
  transactionTypeLabel: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '700',
    color: theme.colors.textSecondary,
  },
  transactionInfoRow: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  transactionDate: {
    fontSize: 12,
    color: theme.colors.textSecondary,
  },
  transactionStatusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  transactionStatusText: {
    fontSize: 10,
    fontWeight: '800',
  },
  transactionAmount: {
    fontSize: 15,
    fontWeight: '800',
    color: theme.colors.text,
  },
  transactionMeta: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
  },
  productText: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    marginBottom: 3,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  primaryAction: {
    flex: 1,
    minHeight: 42,
    borderRadius: 10,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryAction: {
    flex: 1,
    minHeight: 42,
    borderRadius: 10,
    backgroundColor: '#f8f9fa',
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  whatsappAction: {
    minHeight: 42,
    marginTop: 10,
    borderRadius: 10,
    backgroundColor: '#fff9db',
    borderWidth: 1,
    borderColor: '#ffe066',
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryActionText: {
    color: theme.colors.white,
    fontSize: 13,
    fontWeight: '800',
  },
  secondaryActionText: {
    color: theme.colors.text,
    fontSize: 13,
    fontWeight: '800',
  },
  whatsappActionText: {
    color: '#8a5a00',
    fontSize: 12,
    fontWeight: '800',
  },
  emptyBox: {
    backgroundColor: theme.colors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: 20,
    alignItems: 'center',
  },
  emptyText: {
    marginTop: 8,
    color: theme.colors.textSecondary,
    fontWeight: '600',
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: theme.colors.overlay,
  },
  modalCard: {
    backgroundColor: theme.colors.white,
    padding: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: theme.colors.text,
    marginBottom: 14,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: theme.colors.textSecondary,
    marginBottom: 6,
  },
  input: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    marginBottom: 12,
    color: theme.colors.text,
    backgroundColor: '#fafafa',
  },
  inputError: {
    borderColor: theme.colors.danger,
    marginBottom: 4,
  },
  inputErrorText: {
    color: theme.colors.danger,
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 10,
  },
  modalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
});
